Projects/Controllers/MyAccountController.cs
using Projects.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Projects.Controllers
{
    public class MyAccountController : Controller
    {
        // GET: MyAccount
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Login l, string ReturnUrl="")
        {
            //using (DBEntities db = new DBEntities())
            //{
            //    var user = db.Users.Where(a=>a.Username.Equals(l.Username) && a.Password.Equals(l.Password)).FirstOrDefault();
            //    if(user !=null)
            //    {
            //        FormsAuthentication.SetAuthCookie(user.Username, l.RememberMe);
            //        if(Url.IsLocalUrl(ReturnUrl))
            //        {
            //            return Redirect(ReturnUrl);
            //        }
            //        else
            //        {
            //            return RedirectToAction("MyProfile","Home");
            //        }
            //    }


            //}



            if(ModelState.IsValid)
            {
                var isValidUser = Membership.ValidateUser(l.Username, l.Password);
                if(isValidUser)
                {
                    FormsAuthentication.SetAuthCookie(l.Username, l.RememberMe);
                    if(Url.IsLocalUrl(ReturnUrl))
                    {
                        return Redirect(ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index","Home");
                    }
                }
            }



            ModelState.Remove("Password");
                return View();
        }

        [Authorize]
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Projects/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .menu {
            list-style:none;
            float:right;
        }
        .menu li{
            float:left;
        }

        .menu li a{
           padding:5px;
           margin-right:2px;
           background-color:#f3f3f3;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom de l'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
               


                <ul class="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("My Profile", "MyProfile", "Home")</li>
                    <li>@Html.ActionLink("Administrateur", "AdminIndex", "Home")</li>
                    <li>@Html.ActionLink("Secretaire", "SecretaireIndex", "Home")</li>
                    
                    <li>


                        @{
                            if (Request.IsAuthenticated)
                            {
                                using (Html.BeginForm("LogOut", "MyAccount", FormMethod.Post, new { id = "logoutForm" }))
                                {
                                    <text>Welcome <strong>@User.Identity.Name</strong>!</text>
                                    <a href="javascript:document.getElementById('logoutForm').submit()">LogOut</a>
                                    }
                                    }
                                    

                                    }
                                </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()


        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>